### ISSUE TITLE
项目启动编译失败

### ISSUE THREAD

**Issue by cookiy** [djyde/effective-apollo-antd#1]
对项目比较感兴趣，试着下来本地研究了下，遇到一些问题，发个issue问一下

1: yarn安装依赖

2: npm run start启动项目,遇到了ts校验问题，是类型校验问题

类型改动后可以启动，例如改为这样，可以通过

`handleTableChange = (pagination: any) => {
    const pager = { ...pagination };
    pager.current = pagination.current;

    this.setState({ pagination: pager });
  };`

第一个问题，大神的项目启动时类型这块，是直接通过的吗？？

3. 类型校验没有问题，但是编译出了问题，排查了下，说是tsconfig.json里的lib需要添加东西，es5和es6冲突了，改成了这样

`
    "lib": [
      "es6",
      "es2017",
      "dom",
      "esnext",
      "es5",
      "es2015.core",
      "es2015.collection",
      "es2015.generator",
      "es2015.iterable",
      "es2015.proxy",
      "es2015.reflect",
      "es2015.symbol",
      "es2015.symbol.wellknown",
      "esnext.asynciterable"
    ],
`
依然无法编译通过，报错为

`/Users/cookiywang/code/extend/graphql/effective-apollo-antd-master/node_modules/@types/react-router/index.d.ts
(117,50): Cannot find name 'Exclude'.`

第二个问题，大神帮我排查下，问题出在哪，十分感谢

**Comment by djyde** [comment]
试试从 Codesandbox 把项目导下来跑？

**Comment by cookiy** [comment]
> 试试从 Codesandbox 把项目导下来跑？

已经试过了，回答一些踩过的坑

第一个问题是TSLINT的隐式变量需要声明，属于TS的正常操作，类似的TS报错还有很多，大约100个，修复掉就好

第二个问题是应用包版本问题，typescript 2.7.2 update to 2.8.3 fixed react-route problems

剩下的还有一堆问题，基本都是依赖包的版本过低，互相依赖和缺少@type的第三方包，TS的语言校验问题导致

目前我这边项目修好已经跑通，大神你的这个项目，可能因为版本或者语法问题，clone安装后，也会出现跑不起来现象

还是给大神你一个赞，代码很清晰，写的很好
